namespace ui_qlnhahang
{
    partial class Dashboard
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Dashboard));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.pbHeader = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.lblTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnExit = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btnMinimize = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.panel = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnAccManage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnFoodManage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnOpenOrder = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTableManage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCateManage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnBillManage = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.sidebar = new System.Windows.Forms.GroupBox();
            ((System.ComponentModel.ISupportInitialize)(this.pbHeader)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnExit)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnMinimize)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.sidebar.SuspendLayout();
            this.SuspendLayout();
            // 
            // pbHeader
            // 
            this.pbHeader.AllowFocused = false;
            this.pbHeader.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pbHeader.AutoSizeHeight = true;
            this.pbHeader.BackColor = System.Drawing.Color.Transparent;
            this.pbHeader.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pbHeader.BorderRadius = 0;
            this.pbHeader.Image = ((System.Drawing.Image)(resources.GetObject("pbHeader.Image")));
            this.pbHeader.IsCircle = true;
            this.pbHeader.Location = new System.Drawing.Point(249, 12);
            this.pbHeader.Name = "pbHeader";
            this.pbHeader.Size = new System.Drawing.Size(50, 50);
            this.pbHeader.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pbHeader.TabIndex = 0;
            this.pbHeader.TabStop = false;
            this.pbHeader.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // lblTitle
            // 
            this.lblTitle.AllowParentOverrides = false;
            this.lblTitle.AutoEllipsis = false;
            this.lblTitle.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblTitle.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblTitle.Font = new System.Drawing.Font("Tahoma", 27.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle.Location = new System.Drawing.Point(328, 17);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTitle.Size = new System.Drawing.Size(174, 45);
            this.lblTitle.TabIndex = 7;
            this.lblTitle.Text = "Dashboard";
            this.lblTitle.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnExit
            // 
            this.btnExit.AllowFocused = false;
            this.btnExit.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnExit.AutoSizeHeight = true;
            this.btnExit.BorderRadius = 15;
            this.btnExit.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnExit.Image = ((System.Drawing.Image)(resources.GetObject("btnExit.Image")));
            this.btnExit.IsCircle = true;
            this.btnExit.Location = new System.Drawing.Point(1240, 12);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(30, 30);
            this.btnExit.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnExit.TabIndex = 5;
            this.btnExit.TabStop = false;
            this.btnExit.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.btnExit.Click += new System.EventHandler(this.btnExit_Click);
            // 
            // btnMinimize
            // 
            this.btnMinimize.AllowFocused = false;
            this.btnMinimize.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnMinimize.AutoSizeHeight = true;
            this.btnMinimize.BorderRadius = 15;
            this.btnMinimize.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnMinimize.Image = ((System.Drawing.Image)(resources.GetObject("btnMinimize.Image")));
            this.btnMinimize.IsCircle = true;
            this.btnMinimize.Location = new System.Drawing.Point(1202, 12);
            this.btnMinimize.Name = "btnMinimize";
            this.btnMinimize.Size = new System.Drawing.Size(30, 30);
            this.btnMinimize.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnMinimize.TabIndex = 6;
            this.btnMinimize.TabStop = false;
            this.btnMinimize.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.btnMinimize.Click += new System.EventHandler(this.btnMinimize_Click);
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 98;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(12, 19);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(197, 197);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 1;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.bunifuPictureBox1.Click += new System.EventHandler(this.bunifuPictureBox1_Click_1);
            // 
            // panel
            // 
            this.panel.BackgroundColor = System.Drawing.Color.Transparent;
            this.panel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panel.BackgroundImage")));
            this.panel.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panel.BorderColor = System.Drawing.Color.Transparent;
            this.panel.BorderRadius = 3;
            this.panel.BorderThickness = 1;
            this.panel.Location = new System.Drawing.Point(231, 80);
            this.panel.Name = "panel";
            this.panel.ShowBorders = true;
            this.panel.Size = new System.Drawing.Size(1039, 576);
            this.panel.TabIndex = 9;
            this.panel.Click += new System.EventHandler(this.panel_Click);
            // 
            // btnAccManage
            // 
            this.btnAccManage.AllowAnimations = true;
            this.btnAccManage.AllowMouseEffects = true;
            this.btnAccManage.AllowToggling = false;
            this.btnAccManage.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnAccManage.AnimationSpeed = 200;
            this.btnAccManage.AutoGenerateColors = false;
            this.btnAccManage.AutoRoundBorders = false;
            this.btnAccManage.AutoSizeLeftIcon = true;
            this.btnAccManage.AutoSizeRightIcon = true;
            this.btnAccManage.BackColor = System.Drawing.Color.Transparent;
            this.btnAccManage.BackColor1 = System.Drawing.Color.Transparent;
            this.btnAccManage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAccManage.BackgroundImage")));
            this.btnAccManage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccManage.ButtonText = "Quản Lý tài khoản";
            this.btnAccManage.ButtonTextMarginLeft = 0;
            this.btnAccManage.ColorContrastOnClick = 45;
            this.btnAccManage.ColorContrastOnHover = 45;
            this.btnAccManage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnAccManage.CustomizableEdges = borderEdges8;
            this.btnAccManage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAccManage.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnAccManage.DisabledFillColor = System.Drawing.Color.AliceBlue;
            this.btnAccManage.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnAccManage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAccManage.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAccManage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAccManage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAccManage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAccManage.IconMarginLeft = 11;
            this.btnAccManage.IconPadding = 10;
            this.btnAccManage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAccManage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAccManage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAccManage.IconSize = 25;
            this.btnAccManage.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnAccManage.IdleBorderRadius = 1;
            this.btnAccManage.IdleBorderThickness = 1;
            this.btnAccManage.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnAccManage.IdleIconLeftImage = null;
            this.btnAccManage.IdleIconRightImage = null;
            this.btnAccManage.IndicateFocus = false;
            this.btnAccManage.Location = new System.Drawing.Point(-14, 338);
            this.btnAccManage.Name = "btnAccManage";
            this.btnAccManage.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.btnAccManage.OnDisabledState.BorderRadius = 1;
            this.btnAccManage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccManage.OnDisabledState.BorderThickness = 1;
            this.btnAccManage.OnDisabledState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnAccManage.OnDisabledState.ForeColor = System.Drawing.Color.Empty;
            this.btnAccManage.OnDisabledState.IconLeftImage = null;
            this.btnAccManage.OnDisabledState.IconRightImage = null;
            this.btnAccManage.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.btnAccManage.onHoverState.BorderRadius = 1;
            this.btnAccManage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccManage.onHoverState.BorderThickness = 1;
            this.btnAccManage.onHoverState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnAccManage.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.btnAccManage.onHoverState.IconLeftImage = null;
            this.btnAccManage.onHoverState.IconRightImage = null;
            this.btnAccManage.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.btnAccManage.OnIdleState.BorderRadius = 1;
            this.btnAccManage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccManage.OnIdleState.BorderThickness = 1;
            this.btnAccManage.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnAccManage.OnIdleState.ForeColor = System.Drawing.Color.Empty;
            this.btnAccManage.OnIdleState.IconLeftImage = null;
            this.btnAccManage.OnIdleState.IconRightImage = null;
            this.btnAccManage.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.btnAccManage.OnPressedState.BorderRadius = 1;
            this.btnAccManage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAccManage.OnPressedState.BorderThickness = 1;
            this.btnAccManage.OnPressedState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnAccManage.OnPressedState.ForeColor = System.Drawing.Color.Empty;
            this.btnAccManage.OnPressedState.IconLeftImage = null;
            this.btnAccManage.OnPressedState.IconRightImage = null;
            this.btnAccManage.Size = new System.Drawing.Size(248, 52);
            this.btnAccManage.TabIndex = 5;
            this.btnAccManage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAccManage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAccManage.TextMarginLeft = 0;
            this.btnAccManage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAccManage.UseDefaultRadiusAndThickness = true;
            this.btnAccManage.Click += new System.EventHandler(this.btnAccManage_Click);
            // 
            // btnFoodManage
            // 
            this.btnFoodManage.AllowAnimations = true;
            this.btnFoodManage.AllowMouseEffects = true;
            this.btnFoodManage.AllowToggling = false;
            this.btnFoodManage.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnFoodManage.AnimationSpeed = 200;
            this.btnFoodManage.AutoGenerateColors = false;
            this.btnFoodManage.AutoRoundBorders = false;
            this.btnFoodManage.AutoSizeLeftIcon = true;
            this.btnFoodManage.AutoSizeRightIcon = true;
            this.btnFoodManage.BackColor = System.Drawing.Color.Transparent;
            this.btnFoodManage.BackColor1 = System.Drawing.Color.Transparent;
            this.btnFoodManage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFoodManage.BackgroundImage")));
            this.btnFoodManage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFoodManage.ButtonText = "Quản Lý Món Ăn";
            this.btnFoodManage.ButtonTextMarginLeft = 0;
            this.btnFoodManage.ColorContrastOnClick = 45;
            this.btnFoodManage.ColorContrastOnHover = 45;
            this.btnFoodManage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnFoodManage.CustomizableEdges = borderEdges9;
            this.btnFoodManage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFoodManage.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnFoodManage.DisabledFillColor = System.Drawing.Color.AliceBlue;
            this.btnFoodManage.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnFoodManage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnFoodManage.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFoodManage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFoodManage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFoodManage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFoodManage.IconMarginLeft = 11;
            this.btnFoodManage.IconPadding = 10;
            this.btnFoodManage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFoodManage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFoodManage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFoodManage.IconSize = 25;
            this.btnFoodManage.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnFoodManage.IdleBorderRadius = 1;
            this.btnFoodManage.IdleBorderThickness = 1;
            this.btnFoodManage.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnFoodManage.IdleIconLeftImage = null;
            this.btnFoodManage.IdleIconRightImage = null;
            this.btnFoodManage.IndicateFocus = false;
            this.btnFoodManage.Location = new System.Drawing.Point(-14, 280);
            this.btnFoodManage.Name = "btnFoodManage";
            this.btnFoodManage.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.btnFoodManage.OnDisabledState.BorderRadius = 1;
            this.btnFoodManage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFoodManage.OnDisabledState.BorderThickness = 1;
            this.btnFoodManage.OnDisabledState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnFoodManage.OnDisabledState.ForeColor = System.Drawing.Color.Empty;
            this.btnFoodManage.OnDisabledState.IconLeftImage = null;
            this.btnFoodManage.OnDisabledState.IconRightImage = null;
            this.btnFoodManage.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.btnFoodManage.onHoverState.BorderRadius = 1;
            this.btnFoodManage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFoodManage.onHoverState.BorderThickness = 1;
            this.btnFoodManage.onHoverState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnFoodManage.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.btnFoodManage.onHoverState.IconLeftImage = null;
            this.btnFoodManage.onHoverState.IconRightImage = null;
            this.btnFoodManage.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.btnFoodManage.OnIdleState.BorderRadius = 1;
            this.btnFoodManage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFoodManage.OnIdleState.BorderThickness = 1;
            this.btnFoodManage.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnFoodManage.OnIdleState.ForeColor = System.Drawing.Color.Empty;
            this.btnFoodManage.OnIdleState.IconLeftImage = null;
            this.btnFoodManage.OnIdleState.IconRightImage = null;
            this.btnFoodManage.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.btnFoodManage.OnPressedState.BorderRadius = 1;
            this.btnFoodManage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFoodManage.OnPressedState.BorderThickness = 1;
            this.btnFoodManage.OnPressedState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnFoodManage.OnPressedState.ForeColor = System.Drawing.Color.Empty;
            this.btnFoodManage.OnPressedState.IconLeftImage = null;
            this.btnFoodManage.OnPressedState.IconRightImage = null;
            this.btnFoodManage.Size = new System.Drawing.Size(248, 52);
            this.btnFoodManage.TabIndex = 2;
            this.btnFoodManage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFoodManage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFoodManage.TextMarginLeft = 0;
            this.btnFoodManage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFoodManage.UseDefaultRadiusAndThickness = true;
            this.btnFoodManage.Click += new System.EventHandler(this.btnFoodManage_Click);
            // 
            // btnOpenOrder
            // 
            this.btnOpenOrder.AllowAnimations = true;
            this.btnOpenOrder.AllowMouseEffects = true;
            this.btnOpenOrder.AllowToggling = false;
            this.btnOpenOrder.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnOpenOrder.AnimationSpeed = 200;
            this.btnOpenOrder.AutoGenerateColors = false;
            this.btnOpenOrder.AutoRoundBorders = false;
            this.btnOpenOrder.AutoSizeLeftIcon = true;
            this.btnOpenOrder.AutoSizeRightIcon = true;
            this.btnOpenOrder.BackColor = System.Drawing.Color.Transparent;
            this.btnOpenOrder.BackColor1 = System.Drawing.Color.Transparent;
            this.btnOpenOrder.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnOpenOrder.BackgroundImage")));
            this.btnOpenOrder.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpenOrder.ButtonText = "Bắt Đầu Order";
            this.btnOpenOrder.ButtonTextMarginLeft = 0;
            this.btnOpenOrder.ColorContrastOnClick = 45;
            this.btnOpenOrder.ColorContrastOnHover = 45;
            this.btnOpenOrder.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btnOpenOrder.CustomizableEdges = borderEdges10;
            this.btnOpenOrder.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnOpenOrder.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnOpenOrder.DisabledFillColor = System.Drawing.Color.AliceBlue;
            this.btnOpenOrder.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnOpenOrder.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnOpenOrder.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnOpenOrder.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnOpenOrder.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnOpenOrder.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnOpenOrder.IconMarginLeft = 11;
            this.btnOpenOrder.IconPadding = 10;
            this.btnOpenOrder.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnOpenOrder.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnOpenOrder.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnOpenOrder.IconSize = 25;
            this.btnOpenOrder.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnOpenOrder.IdleBorderRadius = 1;
            this.btnOpenOrder.IdleBorderThickness = 1;
            this.btnOpenOrder.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnOpenOrder.IdleIconLeftImage = null;
            this.btnOpenOrder.IdleIconRightImage = null;
            this.btnOpenOrder.IndicateFocus = false;
            this.btnOpenOrder.Location = new System.Drawing.Point(-14, 396);
            this.btnOpenOrder.Name = "btnOpenOrder";
            this.btnOpenOrder.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.btnOpenOrder.OnDisabledState.BorderRadius = 1;
            this.btnOpenOrder.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpenOrder.OnDisabledState.BorderThickness = 1;
            this.btnOpenOrder.OnDisabledState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnOpenOrder.OnDisabledState.ForeColor = System.Drawing.Color.Empty;
            this.btnOpenOrder.OnDisabledState.IconLeftImage = null;
            this.btnOpenOrder.OnDisabledState.IconRightImage = null;
            this.btnOpenOrder.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.btnOpenOrder.onHoverState.BorderRadius = 1;
            this.btnOpenOrder.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpenOrder.onHoverState.BorderThickness = 1;
            this.btnOpenOrder.onHoverState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnOpenOrder.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.btnOpenOrder.onHoverState.IconLeftImage = null;
            this.btnOpenOrder.onHoverState.IconRightImage = null;
            this.btnOpenOrder.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.btnOpenOrder.OnIdleState.BorderRadius = 1;
            this.btnOpenOrder.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpenOrder.OnIdleState.BorderThickness = 1;
            this.btnOpenOrder.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnOpenOrder.OnIdleState.ForeColor = System.Drawing.Color.Empty;
            this.btnOpenOrder.OnIdleState.IconLeftImage = null;
            this.btnOpenOrder.OnIdleState.IconRightImage = null;
            this.btnOpenOrder.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.btnOpenOrder.OnPressedState.BorderRadius = 1;
            this.btnOpenOrder.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnOpenOrder.OnPressedState.BorderThickness = 1;
            this.btnOpenOrder.OnPressedState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnOpenOrder.OnPressedState.ForeColor = System.Drawing.Color.Empty;
            this.btnOpenOrder.OnPressedState.IconLeftImage = null;
            this.btnOpenOrder.OnPressedState.IconRightImage = null;
            this.btnOpenOrder.Size = new System.Drawing.Size(248, 52);
            this.btnOpenOrder.TabIndex = 8;
            this.btnOpenOrder.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnOpenOrder.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnOpenOrder.TextMarginLeft = 0;
            this.btnOpenOrder.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnOpenOrder.UseDefaultRadiusAndThickness = true;
            this.btnOpenOrder.Click += new System.EventHandler(this.btnOpenOrder_Click);
            // 
            // btnTableManage
            // 
            this.btnTableManage.AllowAnimations = true;
            this.btnTableManage.AllowMouseEffects = true;
            this.btnTableManage.AllowToggling = false;
            this.btnTableManage.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnTableManage.AnimationSpeed = 200;
            this.btnTableManage.AutoGenerateColors = false;
            this.btnTableManage.AutoRoundBorders = false;
            this.btnTableManage.AutoSizeLeftIcon = true;
            this.btnTableManage.AutoSizeRightIcon = true;
            this.btnTableManage.BackColor = System.Drawing.Color.Transparent;
            this.btnTableManage.BackColor1 = System.Drawing.Color.Transparent;
            this.btnTableManage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTableManage.BackgroundImage")));
            this.btnTableManage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTableManage.ButtonText = "Quản Lý Bàn";
            this.btnTableManage.ButtonTextMarginLeft = 0;
            this.btnTableManage.ColorContrastOnClick = 45;
            this.btnTableManage.ColorContrastOnHover = 45;
            this.btnTableManage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnTableManage.CustomizableEdges = borderEdges11;
            this.btnTableManage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTableManage.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnTableManage.DisabledFillColor = System.Drawing.Color.AliceBlue;
            this.btnTableManage.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnTableManage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTableManage.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTableManage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTableManage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTableManage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTableManage.IconMarginLeft = 11;
            this.btnTableManage.IconPadding = 10;
            this.btnTableManage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTableManage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTableManage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTableManage.IconSize = 25;
            this.btnTableManage.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnTableManage.IdleBorderRadius = 1;
            this.btnTableManage.IdleBorderThickness = 1;
            this.btnTableManage.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnTableManage.IdleIconLeftImage = null;
            this.btnTableManage.IdleIconRightImage = null;
            this.btnTableManage.IndicateFocus = false;
            this.btnTableManage.Location = new System.Drawing.Point(-14, 454);
            this.btnTableManage.Name = "btnTableManage";
            this.btnTableManage.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.btnTableManage.OnDisabledState.BorderRadius = 1;
            this.btnTableManage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTableManage.OnDisabledState.BorderThickness = 1;
            this.btnTableManage.OnDisabledState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnTableManage.OnDisabledState.ForeColor = System.Drawing.Color.Empty;
            this.btnTableManage.OnDisabledState.IconLeftImage = null;
            this.btnTableManage.OnDisabledState.IconRightImage = null;
            this.btnTableManage.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.btnTableManage.onHoverState.BorderRadius = 1;
            this.btnTableManage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTableManage.onHoverState.BorderThickness = 1;
            this.btnTableManage.onHoverState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnTableManage.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.btnTableManage.onHoverState.IconLeftImage = null;
            this.btnTableManage.onHoverState.IconRightImage = null;
            this.btnTableManage.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.btnTableManage.OnIdleState.BorderRadius = 1;
            this.btnTableManage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTableManage.OnIdleState.BorderThickness = 1;
            this.btnTableManage.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnTableManage.OnIdleState.ForeColor = System.Drawing.Color.Empty;
            this.btnTableManage.OnIdleState.IconLeftImage = null;
            this.btnTableManage.OnIdleState.IconRightImage = null;
            this.btnTableManage.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.btnTableManage.OnPressedState.BorderRadius = 1;
            this.btnTableManage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTableManage.OnPressedState.BorderThickness = 1;
            this.btnTableManage.OnPressedState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnTableManage.OnPressedState.ForeColor = System.Drawing.Color.Empty;
            this.btnTableManage.OnPressedState.IconLeftImage = null;
            this.btnTableManage.OnPressedState.IconRightImage = null;
            this.btnTableManage.Size = new System.Drawing.Size(248, 52);
            this.btnTableManage.TabIndex = 4;
            this.btnTableManage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTableManage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTableManage.TextMarginLeft = 0;
            this.btnTableManage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTableManage.UseDefaultRadiusAndThickness = true;
            this.btnTableManage.Click += new System.EventHandler(this.btnTableManage_Click);
            // 
            // btnCateManage
            // 
            this.btnCateManage.AllowAnimations = true;
            this.btnCateManage.AllowMouseEffects = true;
            this.btnCateManage.AllowToggling = false;
            this.btnCateManage.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnCateManage.AnimationSpeed = 200;
            this.btnCateManage.AutoGenerateColors = false;
            this.btnCateManage.AutoRoundBorders = false;
            this.btnCateManage.AutoSizeLeftIcon = true;
            this.btnCateManage.AutoSizeRightIcon = true;
            this.btnCateManage.BackColor = System.Drawing.Color.Transparent;
            this.btnCateManage.BackColor1 = System.Drawing.Color.Transparent;
            this.btnCateManage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCateManage.BackgroundImage")));
            this.btnCateManage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCateManage.ButtonText = "Quản Lý Danh Mục";
            this.btnCateManage.ButtonTextMarginLeft = 0;
            this.btnCateManage.ColorContrastOnClick = 45;
            this.btnCateManage.ColorContrastOnHover = 45;
            this.btnCateManage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnCateManage.CustomizableEdges = borderEdges12;
            this.btnCateManage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCateManage.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnCateManage.DisabledFillColor = System.Drawing.Color.AliceBlue;
            this.btnCateManage.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnCateManage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCateManage.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCateManage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCateManage.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCateManage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCateManage.IconMarginLeft = 11;
            this.btnCateManage.IconPadding = 10;
            this.btnCateManage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCateManage.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCateManage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCateManage.IconSize = 25;
            this.btnCateManage.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnCateManage.IdleBorderRadius = 1;
            this.btnCateManage.IdleBorderThickness = 1;
            this.btnCateManage.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnCateManage.IdleIconLeftImage = null;
            this.btnCateManage.IdleIconRightImage = null;
            this.btnCateManage.IndicateFocus = false;
            this.btnCateManage.Location = new System.Drawing.Point(-14, 512);
            this.btnCateManage.Name = "btnCateManage";
            this.btnCateManage.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.btnCateManage.OnDisabledState.BorderRadius = 1;
            this.btnCateManage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCateManage.OnDisabledState.BorderThickness = 1;
            this.btnCateManage.OnDisabledState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnCateManage.OnDisabledState.ForeColor = System.Drawing.Color.Empty;
            this.btnCateManage.OnDisabledState.IconLeftImage = null;
            this.btnCateManage.OnDisabledState.IconRightImage = null;
            this.btnCateManage.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.btnCateManage.onHoverState.BorderRadius = 1;
            this.btnCateManage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCateManage.onHoverState.BorderThickness = 1;
            this.btnCateManage.onHoverState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnCateManage.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.btnCateManage.onHoverState.IconLeftImage = null;
            this.btnCateManage.onHoverState.IconRightImage = null;
            this.btnCateManage.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.btnCateManage.OnIdleState.BorderRadius = 1;
            this.btnCateManage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCateManage.OnIdleState.BorderThickness = 1;
            this.btnCateManage.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnCateManage.OnIdleState.ForeColor = System.Drawing.Color.Empty;
            this.btnCateManage.OnIdleState.IconLeftImage = null;
            this.btnCateManage.OnIdleState.IconRightImage = null;
            this.btnCateManage.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.btnCateManage.OnPressedState.BorderRadius = 1;
            this.btnCateManage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCateManage.OnPressedState.BorderThickness = 1;
            this.btnCateManage.OnPressedState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnCateManage.OnPressedState.ForeColor = System.Drawing.Color.Empty;
            this.btnCateManage.OnPressedState.IconLeftImage = null;
            this.btnCateManage.OnPressedState.IconRightImage = null;
            this.btnCateManage.Size = new System.Drawing.Size(248, 52);
            this.btnCateManage.TabIndex = 0;
            this.btnCateManage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCateManage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCateManage.TextMarginLeft = 0;
            this.btnCateManage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCateManage.UseDefaultRadiusAndThickness = true;
            this.btnCateManage.Click += new System.EventHandler(this.btnCateManage_Click);
            // 
            // btnBillManage
            // 
            this.btnBillManage.AllowAnimations = true;
            this.btnBillManage.AllowMouseEffects = true;
            this.btnBillManage.AllowToggling = false;
            this.btnBillManage.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnBillManage.AnimationSpeed = 200;
            this.btnBillManage.AutoGenerateColors = false;
            this.btnBillManage.AutoRoundBorders = false;
            this.btnBillManage.AutoSizeLeftIcon = true;
            this.btnBillManage.AutoSizeRightIcon = true;
            this.btnBillManage.BackColor = System.Drawing.Color.Transparent;
            this.btnBillManage.BackColor1 = System.Drawing.Color.Transparent;
            this.btnBillManage.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBillManage.BackgroundImage")));
            this.btnBillManage.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBillManage.ButtonText = "Quản Lý Hoá Đơn";
            this.btnBillManage.ButtonTextMarginLeft = 0;
            this.btnBillManage.ColorContrastOnClick = 45;
            this.btnBillManage.ColorContrastOnHover = 45;
            this.btnBillManage.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btnBillManage.CustomizableEdges = borderEdges13;
            this.btnBillManage.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBillManage.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnBillManage.DisabledFillColor = System.Drawing.Color.AliceBlue;
            this.btnBillManage.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnBillManage.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBillManage.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBillManage.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBillManage.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBillManage.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBillManage.IconMarginLeft = 11;
            this.btnBillManage.IconPadding = 10;
            this.btnBillManage.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBillManage.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBillManage.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBillManage.IconSize = 25;
            this.btnBillManage.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnBillManage.IdleBorderRadius = 1;
            this.btnBillManage.IdleBorderThickness = 1;
            this.btnBillManage.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnBillManage.IdleIconLeftImage = null;
            this.btnBillManage.IdleIconRightImage = null;
            this.btnBillManage.IndicateFocus = false;
            this.btnBillManage.Location = new System.Drawing.Point(-14, 570);
            this.btnBillManage.Name = "btnBillManage";
            this.btnBillManage.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.btnBillManage.OnDisabledState.BorderRadius = 1;
            this.btnBillManage.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBillManage.OnDisabledState.BorderThickness = 1;
            this.btnBillManage.OnDisabledState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnBillManage.OnDisabledState.ForeColor = System.Drawing.Color.Empty;
            this.btnBillManage.OnDisabledState.IconLeftImage = null;
            this.btnBillManage.OnDisabledState.IconRightImage = null;
            this.btnBillManage.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.btnBillManage.onHoverState.BorderRadius = 1;
            this.btnBillManage.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBillManage.onHoverState.BorderThickness = 1;
            this.btnBillManage.onHoverState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnBillManage.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.btnBillManage.onHoverState.IconLeftImage = null;
            this.btnBillManage.onHoverState.IconRightImage = null;
            this.btnBillManage.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.btnBillManage.OnIdleState.BorderRadius = 1;
            this.btnBillManage.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBillManage.OnIdleState.BorderThickness = 1;
            this.btnBillManage.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnBillManage.OnIdleState.ForeColor = System.Drawing.Color.Empty;
            this.btnBillManage.OnIdleState.IconLeftImage = null;
            this.btnBillManage.OnIdleState.IconRightImage = null;
            this.btnBillManage.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.btnBillManage.OnPressedState.BorderRadius = 1;
            this.btnBillManage.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBillManage.OnPressedState.BorderThickness = 1;
            this.btnBillManage.OnPressedState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnBillManage.OnPressedState.ForeColor = System.Drawing.Color.Empty;
            this.btnBillManage.OnPressedState.IconLeftImage = null;
            this.btnBillManage.OnPressedState.IconRightImage = null;
            this.btnBillManage.Size = new System.Drawing.Size(248, 52);
            this.btnBillManage.TabIndex = 3;
            this.btnBillManage.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBillManage.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBillManage.TextMarginLeft = 0;
            this.btnBillManage.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBillManage.UseDefaultRadiusAndThickness = true;
            this.btnBillManage.Click += new System.EventHandler(this.btnBillManage_Click);
            // 
            // btnHome
            // 
            this.btnHome.AllowAnimations = true;
            this.btnHome.AllowMouseEffects = true;
            this.btnHome.AllowToggling = false;
            this.btnHome.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnHome.AnimationSpeed = 200;
            this.btnHome.AutoGenerateColors = false;
            this.btnHome.AutoRoundBorders = false;
            this.btnHome.AutoSizeLeftIcon = true;
            this.btnHome.AutoSizeRightIcon = true;
            this.btnHome.BackColor = System.Drawing.Color.Transparent;
            this.btnHome.BackColor1 = System.Drawing.Color.Transparent;
            this.btnHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHome.BackgroundImage")));
            this.btnHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.ButtonText = "Giao Diện chính";
            this.btnHome.ButtonTextMarginLeft = 0;
            this.btnHome.ColorContrastOnClick = 45;
            this.btnHome.ColorContrastOnHover = 45;
            this.btnHome.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.btnHome.CustomizableEdges = borderEdges14;
            this.btnHome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHome.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnHome.DisabledFillColor = System.Drawing.Color.AliceBlue;
            this.btnHome.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHome.Font = new System.Drawing.Font("Tahoma", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHome.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnHome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHome.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHome.IconMarginLeft = 11;
            this.btnHome.IconPadding = 10;
            this.btnHome.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHome.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHome.IconSize = 25;
            this.btnHome.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnHome.IdleBorderRadius = 1;
            this.btnHome.IdleBorderThickness = 1;
            this.btnHome.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnHome.IdleIconLeftImage = null;
            this.btnHome.IdleIconRightImage = null;
            this.btnHome.IndicateFocus = false;
            this.btnHome.Location = new System.Drawing.Point(-14, 222);
            this.btnHome.Name = "btnHome";
            this.btnHome.OnDisabledState.BorderColor = System.Drawing.Color.Empty;
            this.btnHome.OnDisabledState.BorderRadius = 1;
            this.btnHome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnDisabledState.BorderThickness = 1;
            this.btnHome.OnDisabledState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnHome.OnDisabledState.ForeColor = System.Drawing.Color.Empty;
            this.btnHome.OnDisabledState.IconLeftImage = null;
            this.btnHome.OnDisabledState.IconRightImage = null;
            this.btnHome.onHoverState.BorderColor = System.Drawing.Color.Empty;
            this.btnHome.onHoverState.BorderRadius = 1;
            this.btnHome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.onHoverState.BorderThickness = 1;
            this.btnHome.onHoverState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnHome.onHoverState.ForeColor = System.Drawing.Color.Empty;
            this.btnHome.onHoverState.IconLeftImage = null;
            this.btnHome.onHoverState.IconRightImage = null;
            this.btnHome.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.btnHome.OnIdleState.BorderRadius = 1;
            this.btnHome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnIdleState.BorderThickness = 1;
            this.btnHome.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnHome.OnIdleState.ForeColor = System.Drawing.SystemColors.ControlText;
            this.btnHome.OnIdleState.IconLeftImage = null;
            this.btnHome.OnIdleState.IconRightImage = null;
            this.btnHome.OnPressedState.BorderColor = System.Drawing.Color.Empty;
            this.btnHome.OnPressedState.BorderRadius = 1;
            this.btnHome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnPressedState.BorderThickness = 1;
            this.btnHome.OnPressedState.FillColor = System.Drawing.Color.AliceBlue;
            this.btnHome.OnPressedState.ForeColor = System.Drawing.Color.Empty;
            this.btnHome.OnPressedState.IconLeftImage = null;
            this.btnHome.OnPressedState.IconRightImage = null;
            this.btnHome.Size = new System.Drawing.Size(248, 52);
            this.btnHome.TabIndex = 9;
            this.btnHome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHome.TextMarginLeft = 0;
            this.btnHome.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHome.UseDefaultRadiusAndThickness = true;
            this.btnHome.Click += new System.EventHandler(this.btnHome_Click);
            // 
            // sidebar
            // 
            this.sidebar.BackColor = System.Drawing.Color.LightSlateGray;
            this.sidebar.BackgroundImageLayout = System.Windows.Forms.ImageLayout.None;
            this.sidebar.CausesValidation = false;
            this.sidebar.Controls.Add(this.bunifuPictureBox1);
            this.sidebar.Controls.Add(this.btnHome);
            this.sidebar.Controls.Add(this.btnAccManage);
            this.sidebar.Controls.Add(this.btnCateManage);
            this.sidebar.Controls.Add(this.btnBillManage);
            this.sidebar.Controls.Add(this.btnOpenOrder);
            this.sidebar.Controls.Add(this.btnFoodManage);
            this.sidebar.Controls.Add(this.btnTableManage);
            this.sidebar.Cursor = System.Windows.Forms.Cursors.Arrow;
            this.sidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.sidebar.ForeColor = System.Drawing.Color.Black;
            this.sidebar.Location = new System.Drawing.Point(0, 0);
            this.sidebar.Margin = new System.Windows.Forms.Padding(0);
            this.sidebar.Name = "sidebar";
            this.sidebar.Size = new System.Drawing.Size(225, 668);
            this.sidebar.TabIndex = 10;
            this.sidebar.TabStop = false;
            // 
            // Dashboard
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.LightBlue;
            this.ClientSize = new System.Drawing.Size(1282, 668);
            this.Controls.Add(this.sidebar);
            this.Controls.Add(this.btnExit);
            this.Controls.Add(this.btnMinimize);
            this.Controls.Add(this.panel);
            this.Controls.Add(this.lblTitle);
            this.Controls.Add(this.pbHeader);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Dashboard";
            this.Text = "Admin";
            this.Load += new System.EventHandler(this.Form1_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pbHeader)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnExit)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnMinimize)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.sidebar.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuPictureBox btnExit;
        private Bunifu.UI.WinForms.BunifuPictureBox btnMinimize;
        private Bunifu.UI.WinForms.BunifuLabel lblTitle;
        private Bunifu.UI.WinForms.BunifuPictureBox pbHeader;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFoodManage;
        private Bunifu.UI.WinForms.BunifuPanel panel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBillManage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCateManage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnOpenOrder;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAccManage;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTableManage;
        private System.Windows.Forms.GroupBox sidebar;
    }
}

